### ISSUE TITLE
Missing documentation: mqtt5

### ISSUE THREAD

**Issue by EricWittmann** [asyncapi/bindings#1]
The main 2.0.0 specification document links to it, but it doesn't exist.  Reference from the 2.0.0 spec:

https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#server-bindings-object

Check the `mqtt5` row in the table - it links to a missing document.

**Comment by fmvilas** [comment]
Thanks for reporting, Eric. Fixed it temporarily by pushing some placeholder information.
