### ISSUE TITLE
[FEATURE REQUEST] Support Microsoft MQ (MSMQ)

### ISSUE THREAD

**Issue by wcbagley** [asyncapi/bindings#10]
Add MSMQ as a named, supported protocol. It is similar to JMS in function. DTC transactions should be out of scope for now and could be added as a separate feature later as the feature may apply to multiple protocols. https://en.wikipedia.org/wiki/Microsoft_Message_Queuing.

**Comment by fmvilas** [comment]
Can you please add more information about it? How do you imagine the protocol binding shape?

**Comment by wcbagley** [comment]
Similar to IBM MQ, MSMQ uses a concept of write servers and read servers. These are usually clustered (primary and backup) behind a load balancer but the spec need not include that. There may be separate clusters per location. (So you write to server cluster in Houston, read from server cluster in Tallahassee.)
There is a concept of message priority.
There is also a concept where the message writer can block until the receiver accepts the message.

**Comment by fmvilas** [comment]
Same as with IBM MQ. We'll have to do some investigation. Any draft binding work would be appreciated.
