### ISSUE TITLE
[FEATURE REQUEST] Message Ordering Definition

### ISSUE THREAD

**Issue by Paul-T-AU** [asyncapi/bindings#11]
**Feature**: Provide the ability to define an optional attribute indicating if the received events should be processed in strict or grouped order (correlated) or if indeed no ordering is required. For example, something like

**ordering: strict|grouped|none**

**Why**: When the business case requires events to be processed in order, brokers that can implement FIFO or support grouped type event queues can be used. Although the broker can ensure that events are delivered in the defined way it would be of benefit to have the consumer aware of the defined ordering. If aware of ordering requirements consumer implementations can ensure that they handle events correctly, that is maintain the defined ordering when processing, including passing the context downstream or handling fault/retry scenarios.  When ordering is not required the consumer may of course choose to process in parallel or across multiple consumer nodes.

**Benefit**: Design time, documentation & runtime benefits can be achieved by understanding the ordering intent of the stream.

**Example Use cases** : Banking, ensuring credit & debits are applied in the correct order. Health, patient admission & treatment. Insurance, claim creation & processing.

**Comment by fmvilas** [comment]
This is definitely something AsyncAPI bindings should have. Are you thinking about a specific protocol?

**Comment by Paul-T-AU** [comment]
Hi Fran, My initial thinking was more at the logical level so the consumer understood the overall ordering intent for the inflight events. But taking this forward and applying to a specific protocol AWS SQS would be a good candidate, since it supports both ordinary & FIFO queues with grouping.

Would it help if I created a draft set of bindings for SQS to show how this could be applied?

**Comment by fmvilas** [comment]
It would definitely help, even if you just post it here :)

**Comment by Paul-T-AU** [comment]
Sure, will do.

**Comment by Paul-T-AU** [comment]
Please find below the fields I think that would be required to connect to both FIFO & Standard queues and also for the intent to be understood. Please note I have only shown those fields required for ordering not the full configuration.

Reading the thread on extensions and the fact that ordering is implemented by more than one broker (but not all) would this be better as a reusable extension?

![sqs-order-example](https://user-images.githubusercontent.com/58927201/72228421-79d01e80-35fa-11ea-8edc-95e264570cc9.png)

Description of field meaning.

<img width="640" alt="sqs-field-description" src="https://user-images.githubusercontent.com/58927201/72228521-71c4ae80-35fb-11ea-9b9a-16c30c6b88b1.png">

**Comment by fmvilas** [comment]
Is this information about the order and deduplication part of the SQS protocol? Is it something you configure on the broker? Is it something you configure on your clients?

I'm asking because if and only if it's part of the protocol then it should be on a binding. Otherwise, it should probably be an extension as you pointed out. Either a generic extension or a specific one for SQS.

**Comment by Paul-T-AU** [comment]
Yes, they are required to be configured client side, I'll look at converting this to an example extension.

**Comment by fmvilas** [comment]
Hey @Paul-T-AU. Did you finally make it an extension? Is there anything I can do to help you forward on this?

**Comment by Paul-T-AU** [comment]
Hi @fmvilas thanks for the nudge, I need to revisit this, so I will use the current lack of travel opportunities to make some time! Will get back to you.

**Comment by Paul-T-AU** [comment]
So, to bring this conversation back to one location after I strayed over to slack, I just wanted to make sure I’m clear of the intent of bindings versus extensions before I create a push request.

Some SQS Background,

1. When talking about SQS the underlying protocol is HTTP with json/xml/unformatted text for message payload plus message meta attributes.
2. To **publish** to an SQS **FIFO** queue you need to provide the MessageGroupId & depending on queue configuration MessageDeduplicationId as well as some common config attributes. These aren’t directly configurable on the AWS SQS Broker but are baked into the FIFO queue being created.

So, my understanding at the current time is as this configuration is required specifically for AWS SQS and is related to an operation i.e. **publish** it belongs in the SQS Operation Binding. If, however this was a change actually at the protocol level, HTTP in this case, for example a new verb is required, that would then be done via an HTTP extension.

Have I got that right or am I still confused?

**Comment by fmvilas** [comment]
You got it correctly. I think in this case a protocol binding makes sense because it's a protocol on top of http. It may not be the wire protocol but it's still a protocol. I think the example you shared with me is good. Feel free to submit a pull request and we can discuss over code :)

**Comment by fmvilas** [comment]
I'm closing this issue as this has been implemented as an extension here: https://github.com/asyncapi/extensions-catalog/pull/8. Thanks, @Paul-T-AU! 🙌
