### ISSUE TITLE
HTTP message headers vs Message object headers

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/bindings#158]
Given that the native [message object allows you to define headers](https://www.asyncapi.com/docs/reference/specification/v2.5.0#messageObject), what's the reason behind having the [HTTP message bindings](https://github.com/asyncapi/bindings/tree/master/http#message-binding-object) define their own property for defining headers?

**Comment by derberg** [comment]
this is a good question 🤔 
@fmvilas I can't figure that out from commit history

**Comment by fmvilas** [comment]
Yeah, I think this is just because I completely forgot about it when creating the HTTP binding. We should definitely remove it in favor of message headers IMHO.

**Comment by jonaslagoni** [comment]
Ahhh, that makes sense!

Wonder if we should include this piece of information in the bindings? 🤔

**Comment by fmvilas** [comment]
Yeah, wouldn't hurt to remind it there. We saw it can be easily forgotten 😄

**Comment by jonaslagoni** [comment]
Reason for the difference can be read here: https://github.com/asyncapi/bindings/issues/158#issuecomment-1567945989
