### ISSUE TITLE
Pulsar bindings for AsyncAPI

### ISSUE THREAD

**Issue by austek** [asyncapi/bindings#164]
#### Reason/Context
Apache® Pulsar™ is a distributed, open source pub-sub messaging and streaming platform.
Ability to use AsyncApi spec to manage (versioning, schema, bindings, code generation, etc) the platform will be invaluable to organisations.

#### Description
A new AsyncAPI binding for Pulsar to be provided, possibly mirroring the same approach used for all other bindings

**Comment by VisualBean** [comment]
Ive been secretly working on a potential pulsar binding for the passed week or so. Perhaps we can collab @austek
