### ISSUE TITLE
RSocket bindings

### ISSUE THREAD

**Issue by anragab** [asyncapi/bindings#18]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  RSocket is a reactive protocol
- How will this change help?
  Ability to define the type of the channel to be opened for an operation 
  - Send and Forget
  - Send one, receive one
  - Send one, receive many
  - Send many, receive many
  Ability to define which server to create (TCP, or Websocket)
- What is the motivation? 
   Write an RSocket generator

#### Description
Please try answering few of those questions
- What changes have to be introduced?
  - Operation Bindings
  - Server Bindings
- Will this be a breaking change?
  No
- How could it be implemented/designed?
  Add new bindings specification

**Comment by linghengqian** [comment]
Should this issue be handed over to the Rsocket community?

**Comment by derberg** [comment]
@linghengqian we can reopen this issue, not a problem. We just need someone to contribute the binding details. I or other maintainers can offer some onboarding but we definitely are not competent enough to specify what bindings are needed exactly in the case of Rsocket. I hear the name for the first time 😅
