### ISSUE TITLE
Remove all JSON Schema files after spec 3.0 release

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/bindings#183]
#### Reason/Context
After spec 3.0 release all schema files will be located in the spec-json-schema repository, where all codeowners for the bindings will also become codeowners for their respectful bindings. 

https://github.com/asyncapi/spec-json-schemas/tree/next-major-spec/bindings

Therefore we need to remove the schema files from this repository.

**Comment by jonaslagoni** [comment]
This issue closes https://github.com/asyncapi/bindings/issues/113 as well.

**Comment by sambhavgupta0705** [comment]
Hi Jonas I would like to work on this one.

**Comment by sambhavgupta0705** [comment]
@jonaslagoni to resolve this issue I need to remove folders like this
https://github.com/asyncapi/bindings/tree/master/ibmmq/json_schemas

**Comment by jonaslagoni** [comment]
Yes exactly 👍 

Remember this will most likely not be merged until after the spec 3.0 release in June 🙂

**Comment by sambhavgupta0705** [comment]
okay so you are saying that this will be merged after spec 3.0 release in June?

**Comment by jonaslagoni** [comment]
Yes, so you can start the PR up with no problem, but don't expect much activity before that 🙂

**Comment by sambhavgupta0705** [comment]
okay no issues with that.

**Comment by sambhavgupta0705** [comment]
Still relevant
