### ISSUE TITLE
[📑 Docs]: Readme.md, section MQTT bindings / Server Binding Object

### ISSUE THREAD

**Issue by vhe1** [asyncapi/bindings#192]
### What Dev Docs changes are you proposing?

I would like to suggest a clarification for the cleanSession field:
It should be made clear whether it means:
- that the server (the entity providing the API) connects to the broker using `cleanSession=true/false` or
- that the client (the entity using the api) MUST/SHOULD/MAY connect to the broker usign `cleanSession = true/false`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derberg** [comment]
AsyncAPI document should describe what user can do with it. So `that the client (the entity using the api) MUST/SHOULD/MAY connect to the broker usign cleanSession = true/false`

**Comment by vhe1** [comment]
Ok, but the client can do that anyway. Why would it need to be specified at all then?

**Comment by derberg** [comment]
AsyncAPI documents are source not only for docs but code generation too.

**Comment by derberg** [comment]
@vhe1 can this be closed then?

**Comment by vhe1** [comment]
Yes.
