### ISSUE TITLE
[Docs Bug 🐞 report]: HTTP Binding: `type`: Request vs Response

### ISSUE THREAD

**Issue by Lazzaretti** [asyncapi/bindings#212]
### Describe the bug you found in AsyncAPI Docs.

 HTTP Binding: `type`: Request vs. Response is not described. What is the request, and what is the response?

The doc states: `REQUIRED. Type of operation. Its value MUST be either request or response.`

I attached a small sample below. In this sample, does `request` mean the subscriber requests the message (consumer calls channel; response is the message) or the channel sends a request to the subscriber (channel calls consumer; event is attached)?

```
asyncapi: 2.6.0
info:
  title: Event Push API
  version: 1.0.0
channels:
  /event:
    subscribe:
      bindings:
        http:
          type: request # todo: request or response?
          method: POST
      message:
        payload:
          type: string
          examples:
            - "hello"
```

### Attach any resources that can help us understand the issue.

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonaslagoni** [comment]
As of v3 this field is no longer necessary and has been removed from the HTTP bindings. Checkout the request/reply documentation for further information: https://www.asyncapi.com/docs/tutorials/getting-started/request-reply
