### ISSUE TITLE
Implement GitHub Action to Validate examples Field in Schemas

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/bindings#217]
### Background/Context
In the current state, nearly all schemas within our bindings include an `examples` field. Automating the validation of these examples against their respective schemas can serve as a proactive measure to identify incorrect or incomplete schemas.

### Objective
Implement a GitHub Action that automates the validation of the `examples` field in modified or newly added `.json` schemas. This action should be triggered at the Pull Request level to ensure the integrity of changes before they are merged.

### Requirements

1. **Trigger**: The GitHub Action should run whenever a Pull Request is created or updated.
2. **Scope**: Only `.json` files that have been modified or added in the PR should be considered for validation.
4. **Feedback**: If validation fails, the action should comment on the PR indicating which files have issues.

**Comment by Min2who** [comment]
We need to create the action in a new file and not on existing yml file right?

**Comment by KhudaDad414** [comment]
@Min2who yes exactly, we need a new workflow.

**Comment by Min2who** [comment]
ok working in it

**Comment by Min2who** [comment]
this issue should be closed here and should be reopened in the `spec-json-schemas ` repo as this #183 remove all `json` schemas to `spec-json-schemas `

**Comment by KhudaDad414** [comment]
@Min2who you are right.
