### ISSUE TITLE
Kafka bindings document contains conflict merge "leftovers"[Docs Bug 🐞 report]: 

### ISSUE THREAD

**Issue by pkonopacki1** [asyncapi/bindings#218]
### Describe the bug you found in AsyncAPI Docs.

https://github.com/asyncapi/bindings/tree/master/kafka#fixed-fields-3 table contains "<<<<<<< HEAD" and other leftovers from merging conflicted files.

### Attach any resources that can help us understand the issue.

<img width="1026" alt="Screenshot 2023-11-06 at 19 06 29" src="https://github.com/asyncapi/bindings/assets/17990597/ede94521-c0d7-4cec-8cc8-867d5aac90f3">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lbroudoux** [comment]
Hey! Thanks for reporting this. We recently figured it out (see https://github.com/asyncapi/bindings/issues/182#issuecomment-1791353808) and it will be handled as part of the update of Kafka bindings for v3 support.

**Comment by pkonopacki1** [comment]
Ok, thank I would just close the isse and remove my pr.
