### ISSUE TITLE
[Docs Bug 🐞 report]: Formatting for message binding object

### ISSUE THREAD

**Issue by CynthiaPeter** [asyncapi/bindings#222]
### Describe the bug you found in AsyncAPI Docs.

Jose pointed out the formatting issues on the bindings with Kafka page. The screenshot below shows the current formatting.

![image](https://github.com/asyncapi/bindings/assets/33583060/218c4cb3-b87c-43d6-8401-51905cb3eeb1)

### Attach any resources that can help us understand the issue.

Link to the section that needs the update: https://github.com/asyncapi/bindings/blob/master/kafka/README.md#fixed-fields-3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by derberg** [comment]
already fixed
