### ISSUE TITLE
Enable additionalProperties for kafka topicConfigurationObject

### ISSUE THREAD

**Issue by gokerakc** [asyncapi/bindings#231]
#### Reason/Context

Currently, only 5 topic configuration properties are supported by the asyncapi kafka binding (json schema [here](https://github.com/asyncapi/spec-json-schemas/blob/master/bindings/kafka/0.4.0/channel.json#L28)).

These properties are;

- **cleanup.policy**
- **retention.ms**
- **retention.bytes**
- **delete.retention.ms**
- **max.message.bytes**

But in some cases, there is a need to specify vendor-specific topic configurations (e.g. [confluent-topic-configs](https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html)). For that reason I think it makes sense to increase the version of that binding and enable **additionalProperties** for the **topicConfigurationObject**.

In my use case, I need to use the following additional properties and they can also be added to the **topicConfigurationObject** if you see a good fit. Please see the properties from the vendor and proposed property names for the **topicConfigurationObject**:

- confluent.key.schema.validation (`schema.key.validation.enabled`)
- confluent.key.subject.name.strategy (`schema.key.lookup.strategy`)
- confluent.value.schema.validation (`schema.value.validation.enabled`)
- confluent.value.subject.name.strategy (`schema.value.lookup.strategy`)

Please share your thoughts about enabling additional properties and adding these optional properties to the object.

**Comment by gokerakc** [comment]
@lbroudoux I would like to get your thoughts on this because you [commented](https://github.com/asyncapi/bindings/pull/228#issuecomment-1839488931) about adding new properties before.

**Comment by derberg** [comment]
looks like completed
