### ISSUE TITLE
Bindings: "message" of MQTT server binding is defined in the example but not in schema table

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/bindings#33]
Issue part of asyncapi/asyncapi#397

https://github.com/asyncapi/bindings/blob/master/mqtt/README.md#server-binding-object
https://github.com/asyncapi/bindings/blob/master/mqtt/README.md#example

**Comment by BlockLucas** [comment]
Hi! we could create a PR, but we dont know if we should remove the message property from example, or add the message property in the schema.
@fmvilas could you check it up?

**Comment by fmvilas** [comment]
Good catch, @BlockLucas. I think "message" should be added to the table of properties. In other words, the example is correct.
