### ISSUE TITLE
Specify Avro encoding approach

### ISSUE THREAD

**Issue by dalelane** [asyncapi/bindings#40]
There is a need to describe the Avro encoding when using Apache Avro as the payload schema format.

For context, when using an Avro schema to serialize data, a Kafka producer can choose between [two ways of encoding the data](https://avro.apache.org/docs/current/spec.html#Encodings):

- json - the data is still human-readable which is sometimes useful
- binary - the encoded data is smaller and can be faster to deserialize

A Kafka consumer needs to know which encoding mechanism was used to be able to deserialize the messages. 

One of the most commonly used Kafka serializer libraries, Confluent's `io.confluent.kafka.serializers.KafkaAvroSerializer`, only [supports binary encoding](https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java#L103), so I think it's reasonable to assume binary as a default where not specified, and not try to treat this as a required field. 

But it should be possible to specify when json encoding is being used with other serdes libraries [such as Apicurio's](https://github.com/Apicurio/apicurio-registry/blob/0195ace9f4929361114e215787bd0c7d916fdef2/utils/serde/src/main/java/io/apicurio/registry/utils/serde/AvroEncoding.java#L20-L40)

([related Slack question](https://asyncapi.slack.com/archives/C34F2JV0U/p1608292454066500))

Fran's suggestion in Slack was that capturing this in the operation binding would allow this to be specified at the topic level.

**Comment by dalelane** [comment]
I had a go at illustrating what this would look like. It got a bit long, so instead of putting it in a super-long comment here, I've put it in a stand-alone gist at https://gist.github.com/dalelane/3931c17b14c51fa4a1cf25496237d188 

(I also addressed the related issue #41 as part of the same exploration)

**Comment by derberg** [comment]
@dalelane is it Kafka specific only? why not on schemaFromat level?

**Comment by dalelane** [comment]
Yeah, that's a fair point. I've only heard of this being an issue in Kafka, but in theory there's no technical reason why it only could apply to Kafka

**Comment by derberg** [comment]
at the end you just need to specify in the document what content type is sent over the wire right? like `avro/binary` and the schema format would still be json or yml, or?

**Comment by dalelane** [comment]
@derberg When you're using a schema registry (which is the most common approach when Kafka developers are using Avro schemas), developers will specify the ID and version for the schema they're using. There are lots of different places that this can be specified. 

It could be in a header. Or it could be in the message body - typically this is done by prefixing the rest of the message body with it, as some number of bytes are allocated before the rest of the message contents for ID and version. But there are different conventions in the Kafka ecosystem for how many bytes to use to do this.

The challenge here is that you don't know how to parse/deserialise the message body without knowing the convention that was used. 

e.g. If the message publisher put the schema ID and version in the message body, and used two bytes to do this, 
then the message subscriber needs to know to skip the first two bytes of the message body and then use Avro to deserialize only the data after that. (Even if you already have the schema, provided through AsyncAPI, to be able to do the deserialize at all you will still at least need to know to swallow the first couple of bytes, as they're not part of the Avro-serialized data)

**Comment by derberg** [comment]
It does sound tricky, would love to see this on the code level, might be useful to figure out how to present it then in the AsyncAPI file to generate a given code. 

Did you explore the Java template we have (not Spring one). It needs some love and we are looking for maintainers there 😆

**Comment by dalelane** [comment]
@derberg Where is the Java template, please? I was only aware of the two Spring generators (Java Spring and Java Spring Cloud Stream)

**Comment by derberg** [comment]
oh, sorry for confusion, not `not Spring one` I meant not `Java Spring Cloud Stream`

**Comment by dalelane** [comment]
@derberg Brill, thanks. I had a go at [adding support for the new security scheme types](https://github.com/asyncapi/java-spring-template/pull/158) as a way of familiarising myself with the generator

**Comment by derberg** [comment]
@dalelane are you still working on this one?

**Comment by dalelane** [comment]
This will be addressed by https://github.com/asyncapi/bindings/pull/115

**Comment by dalelane** [comment]
closing as I think this has been covered by the changes in #115
