### ISSUE TITLE
SNS/SQS Bindings

### ISSUE THREAD

**Issue by iancooper** [asyncapi/bindings#43]
#### Reason/Context
The standard needs a way to describe bindings for AWS, in particular usage of SNS as a router and SQS as a channel.

Some aspects vary a little from the way AMQP 0.91 (RMQ) works. For example, we don't have a uri for a broker. We do have a URI for a topic in SNS, and we could think about the base part of that path (addressing a host region and account) as the uri and the topic portion of the address separately.

We are looking to adopt AsyncAPI and have a considerable dependency on SNS + SQS and a desire to use desired state built from an AsynAPI description to ensure the infrastructure exists.

The alternative, allowing everyone to interpret SNS + SQS requirements by themselves doesn't present opportunities for OSS tooling to develop around this standard for provisioning on AWS.

#### Description
We may want to discuss approaches to this. Here has visibility, though the Slack may be useful for conversations about them.

We probably want to trial against tooling, to see how easy it is to parse and create the relevant infrastructure. That would form an effective test of the proposal

**Comment by derberg** [comment]
@iancooper as you can see there are no bindings defined for SNS and SQS, so feel free to open a PR

**Comment by derberg** [comment]
@iancooper do you plan to work on this one, should I fight the stale bot or just let it be closed and you just reopen when you have time to jump into it?

**Comment by iancooper** [comment]
@derberg Hopefully some time this week, but let's close and re-open when i get it done
