### ISSUE TITLE
Clarify schema restriction on WebSocket Bindings query

### ISSUE THREAD

**Issue by fujiapple852** [asyncapi/bindings#66]
The documentation for [WebSockets Bindings](https://github.com/asyncapi/bindings/blob/master/websockets/README.md) states that the `query' must be:

> A Schema object containing the definitions for each query parameter. This schema MUST be of type object and have a properties key.

I am attempting to encode an existing WebSocket API which establishes the connection with a POST request which has a body that is a JSON array. This appears to be accepted by several validators (I can produce an example if required) yet is not allowed by the specification.

Is the restriction as documented accurate?

**Comment by derberg** [comment]
@fujiapple852 it would be great to get an example. You can rework this one.

Also keep in mind that validators do not support bindings yet. So whatever goes in is treated as valid

**Comment by fujiapple852** [comment]
@derberg Apologies for the delay and thank you for the assistance.

Here is an example of a trivial `bindings` object which specifies that a `POST` operation with a `query` (which I interpret as the body of the `POST` as there is no separate `body` field specified) is an `array` of `string`:

```json
{
  "ws": {
    "method": "POST",
    "query": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "bindingVersion": "0.1.0"
  }
}
```

Here is the sample example embedded in a minimal valid AsyncAPI document:

```json
{
  "asyncapi": "2.0.0",
  "info": {
    "title": "Test",
    "version": "1.0.0"
  },
  "channels": {
    "myChannel": {
      "subscribe": {
        "operationId": "myOperation",
        "message": {
          "contentType": "application/json",
          "payload": {
            "$ref": "#/components/schemas/Events"
          }
        }
      },
      "bindings": {
        "ws": {
          "method": "POST",
          "query": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "bindingVersion": "0.1.0"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Events": {}
    }
  }
}
```

The example appears to violate the specification because the `schema` object has the type `array` rather than the type required type `object`.

As you point out, the validators do not support bindings yet and so I would like to confirm if the example above is intended to be valid in the specification (and if not what the correct alternative representation should be)?

**Comment by derberg** [comment]
> You can rework this one

of course I did not provide a link to an example, 🤦🏼 , sorry

Look at this example I created recently -> https://github.com/asyncapi/spec/blob/master/examples/2.0.0/websocket-gemini.yml#L63 It is object. Another old example -> https://raw.githubusercontent.com/asyncapi/generator/v1.4.0/test/docs/ws.yml

Why you prefer Array over Object? or another question why do you expect only an Object. It is not directly required in the binding. It must be a valid Schema Object, but can be of any type

> The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is a superset of the JSON Schema Specification Draft 07.

In future once we add validation it will work this way that someone provides a schema in `query` and we validate that it is a valid schema object (https://github.com/asyncapi/asyncapi-node/blob/master/schemas/2.0.0.json#L359)

**Comment by fujiapple852** [comment]
@derberg thanks for the example.

> Why you prefer Array over Object?

No preference but I have an existing WS API that works this way and I am trying to produce an asyncapi document for it.

> or another question why do you expect only an Object. It is not directly required in the binding

The [WebSockets Bindings](https://github.com/asyncapi/bindings/blob/master/websockets/README.md) document which is linked from the main asyncapi specification contains the quote from my original question, which led me to believe it must be an `object`.  

Great to hear that any valid SON Schema Specification Draft 07 object is allowed, perhaps then we just need to update the language in the document I linked to to avoid confusion?

Aside, do you know if there is an intent to move to the latest JSON Schema draft (2020-12) to align with OpenAPI 3.1?

**Comment by derberg** [comment]
@fujiapple852 

> Aside, do you know if there is an intent to move to the latest JSON Schema draft (2020-12) to align with OpenAPI 3.1?

I don't recall any specific discussion, feel free to create an issue in the `spec` repo.

> perhaps then we just need to update the language in the document I linked to to avoid confusion?

feel free to open a PR with a suggestion.

**Comment by derberg** [comment]
@fujiapple852 hey, sorry, actually it must be type object, I just checked that this is what binding says 

```
A Schema object containing the definitions for each query parameter. This schema MUST be of type object and have a properties key.
```

**Comment by bali182** [comment]
@fujiapple852 Hello, we just had a chat with @derberg about a very similar issue, I'm curious in your example how would the query string look like that's built from this array? I was under the impression that the `query` field is an object, and each field represents a separate query parameter. Eg.:

{
  "ws": {
    "method": "POST",
    "query": {
      "type": "object",
      "properties": {
        "foo": { "type": "string" },
        "bar": { "type": "number" },
        "blah": { "type": "boolean" }
      }
    },
    "bindingVersion": "0.1.0"
  }
}


Meaning you have to connect with a query string such as:

```
...?foo=somestring&bar=20&balh=false
```

What does the query string look like in your case that would require an array?

**Comment by fujiapple852** [comment]
@bali182 My original question is bogus (I had misunderstood the API I was trying to encode, it does not `POST` anything).  

Checking [RFC 6455](https://datatracker.ietf.org/doc/html/rfc6455) it says (bottom of page 16, point 2) that:

> The method of the request MUST be GET, and the HTTP version MUST be at least 1.1.

So I think the only (minor) issue here is that the [WebSockets Bindings](https://github.com/asyncapi/bindings/blob/master/websockets/README.md) states that:

> The HTTP method to use when establishing the connection. Its value MUST be either GET or POST.

Do you agree?

**Comment by bali182** [comment]
Ah I think we meant different things then. Hmm to me intuitively POST would make sense in case you wanna send a larger amount of data when connecting, but I'm just playing with sockets atm, haven't read the specs.

**Comment by fujiapple852** [comment]
@bali182 i agree it makes sense to support POST (and with it the ability to provide an arbitrary body, including a JSON array!) but it seems the WS spec forbids it for some reason, or at least so it seems from my limited reading!  I’ll leave the question of whether it makes sense for asyncapi to allow POST to those better informed than I am on the matter. 

in any case my original question has been answered and so I think this issue can be closed.
