### ISSUE TITLE
AMQP: Unable to use $ref for queue or exchange

### ISSUE THREAD

**Issue by olvlvl** [asyncapi/bindings#7]
Hi everyone,

Using RabbitMQ, many messages are published to the same exchange, and many messages are read from the same queues. I would expect to be able to use `$ref` to share exchanges and queues definitions between channels but using the keyword produces a parsing error:

![Screen Shot 2019-11-07 at 16 19 44](https://user-images.githubusercontent.com/155998/68401682-7348a500-017a-11ea-80f1-60fb0f387f8b.png)

Could we consider allowing `$ref` in there? Here's an example:

```yaml
asyncapi: 2.0.0
info:
  title: recipes-service
  version: latest
channels:
  recipe.activated:
    publish:
      message:
        $ref: '#/components/messages/pubRecipeActivated'
    subscribe:
      message:
        $ref: '#/components/messages/subRecipeActivated'
    bindings:
      amqp:
        is: routingKey
        queue:
          $ref: '#/components/queues/events'
        exchange:
          $ref: '#/components/exchanges/primary'

components:
  exchanges:
    primary:
      name: recipes-service
      type: topic
      durable: true
      autoDelete: false

  queues:
    events:
      name: recipes-service.events
      durable: true
      exclusive: true
      autoDelete: false

  messages:
    pubRecipeActivated:
      summary: A recipe was activated
    subRecipeActivated:
      summary: A recipe was activated
```

**Comment by fmvilas** [comment]
Hey Olivier! It's possible to use `$ref` there. Actually, `$ref` is a JSON Schema mechanism, not an AsyncAPI-specific one.

What's not allowed, is to have `exchanges` or `queues` under `components` but nothing stops you from having your own `x-components` section in the document. Like this:

```yaml
asyncapi: 2.0.0
info:
  title: recipes-service
  version: latest
channels:
  recipe.activated:
    publish:
      message:
        $ref: '#/components/messages/pubRecipeActivated'
    subscribe:
      message:
        $ref: '#/components/messages/subRecipeActivated'
    bindings:
      amqp:
        is: routingKey
        queue:
          $ref: '#/x-components/queues/events'
        exchange:
          $ref: '#/x-components/exchanges/primary'

x-components:
  exchanges:
    primary:
      name: recipes-service
      type: topic
      durable: true
      autoDelete: false

  queues:
    events:
      name: recipes-service.events
      durable: true
      exclusive: true
      autoDelete: false

components:
  messages:
    pubRecipeActivated:
      summary: A recipe was activated
    subRecipeActivated:
      summary: A recipe was activated
```

Also, you can use $ref to point to an external YAML or JSON file where you can have all these definitions shared across documents. The external file doesn't need to have a specific syntax, just a plain YAML/JSON file.

Hope it helps!

**Comment by olvlvl** [comment]
It completely helps! But I'm not sure it's obvious. Do you think that's something we could mention in the documentation?

**Comment by fmvilas** [comment]
It would definitely be useful in the docs. Maybe not on the spec itself but on the Getting started guide or as a tutorial. Maybe a blog post too. If you're in the mood to write it we can publish it on the AsyncAPI blog 😊
