### ISSUE TITLE
Socket.IO protocol support

### ISSUE THREAD

**Issue by dedoussis** [asyncapi/bindings#74]
#### Reason/Context

Socket.IO is yet another [protocol](https://github.com/socketio/socket.io-protocol) that may be modelled using AsyncAPI. With the current binding specification, a Socket.IO API developer needs to resort to the WebSockets bindings in order to express the schemata of the HTTP header and query param that a Socket.IO server expects upon handshake.

#### Description

My proposal introduces Socket.IO specific bindings through an explicit `socketio` field in the bindings object of all AsyncAPI structures that include the `bindings` field.

Socket.IO bindings MAY only be included at the server or channel level. The inclusion of bindings at the channel level signals the client to [force a new connection](https://socket.io/docs/v4/client-initialization/#forceNew) upon connecting to that channel ([namespace](https://socket.io/docs/v4/namespaces)).

Since a new field is going to be added, this is a backwards compatible proposal.

**Comment by derberg** [comment]
@dedoussis in case you want to take this forward we would definitely have to see how proposed binding would look like, example asyncapi files and reasoning behind those

**Comment by derberg** [comment]
@dedoussis hey, are you still interested to push this forward?
