### ISSUE TITLE
Feature request: Solace bindings

### ISSUE THREAD

**Issue by damaru-inc** [asyncapi/bindings#80]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  At Solace we are expanding our use of AsyncAPI from code generation to discovery and beyond. We need a way to represent things like queue configuration.
- How will this change help?
 It will allow us to represent the details needed to describe more technical features of messaging with Solace.
- What is the motivation?
We see that there already exist bindings for protocols/products such as IBMMQ and Kafka, and we would like to do something similar for Solace. It will allow us to use AsyncAPI in more use cases.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
 We will provide a new page for the Solace bindings.
- Will this be a breaking change?
 No.
- How could it be implemented/designed?
Here is the proposed page: https://github.com/damaru-inc/bindings/tree/solace-bindings-initial/solace

**Comment by derberg** [comment]
@damaru-inc you should definitely go ahead and open up a PR so we can view the proposal there to leave comments. We just release 2.2 release candidate wit Anypoint MQ binding from MuleSoft, so IBMMQ now is not the only one.
