### ISSUE TITLE
JMS Bindings

### ISSUE THREAD

**Issue by rcarrascosps** [asyncapi/bindings#87]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
JMS is very well known in the industry, there are a lot of implementations of it (IBM, Oracle, JBOSS, etc). And it is still used and very reliable for mission critical systems

- How will this change help?
It will allow us to represent the details needed to describe more technical features of messaging with JMS.

- What is the motivation?
We know JMS. We have implemented JMS in several projects. We know the protocol and in the other hand, the JMS protocol is very well known and used in the market. Systems are and will be still created with JMS as their messaging protocol for event driven architectures.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
We will provide a new page for the JMS bindings.
- Will this be a breaking change?
No.
- How could it be implemented/designed?
We will pretty much do a similar thing to what we have in the other bindings

**Comment by derberg** [comment]
JMS binding placeholder is there so feel free to elaborate more on what changes you want to introduce
