### ISSUE TITLE
[FEATURE REQUEST] Support IBM MQ

### ISSUE THREAD

**Issue by wcbagley** [asyncapi/bindings#9]
Would like to add support for IBM MQ as a protocol type. See https://en.wikipedia.org/wiki/IBM_MQ

**Comment by fmvilas** [comment]
Can you please add more information about it? Is it really a protocol or a product implementing protocols like AMQP? How do you imagine the protocol binding shape?

**Comment by wcbagley** [comment]
IBM MQ is the grandaddy of all queing systems. It has some unique features because it exists on both mainframe and open systems, and is often used to pass data between them. So you can write to a queue in EBCDIC and read it from a different server in ASCII. In fact, this may provide justification for the "request/response" sections of the AsyncAPI file because while the schema should be the same, severs are separated by whether they are "write" or "read" servers and the data format (ASCII/EBCDIC) supported by each.
There is also a concept of datagram (one way) messages and request/response message pairs, where you can mark a message as being a request or a response. You need to add a correlation ID to the message so you can pair the response with your request. There may be some opportunity to include request and response schemas/queues/servers similar to OpenAPI.
Datagram types are just strings so any serialized data works, although the mainframe often uses fixed-length fields as data schema.

**Comment by fmvilas** [comment]
Awesome. It looks like it will require some investigation work from our side. Any draft binding work would be appreciated.

**Comment by integrationsolutions** [comment]
IBM MQ is the most used messaging and queuing mechanism in the world. It would be good to see a way to define IBM MQ queues and channels thru asyncapi

**Comment by fmvilas** [comment]
Agree. We don't have much knowledge on IBM MQ though so any help would be appreciated. Pull requests are welcome.
